(() => {
//If you want to add more images, add the link name and URL image URL in the array list below.
	const images_list = [
{
    "url": "https://html-generator.com/uploads/images/2023/03/25/19616D5LNBRXENS.png",
    "alt": "",
    "name": "1",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/03/25/218713VMM7_AJLX.png",
    "alt": "",
    "name": "2",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/03/25/22433ASV2A5OC39.png",
    "alt": "",
    "name": "3",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/03/25/36004YV7X8P1PEB.png",
    "alt": "",
    "name": "4",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/03/25/37438AAQTX3828C.png",
    "alt": "",
    "name": "5",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/03/25/390562Y9NJEOOXA.png",
    "alt": "",
    "name": "6",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/03/25/40535OLX3R1YWLO.png",
    "alt": "",
    "name": "7",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/03/25/412827UNBP0LK1C.png",
    "alt": "",
    "name": "8",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/03/25/613718W0ODY04L4.png",
    "alt": "",
    "name": "9",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/03/25/58399U3EA3HP5HQ.png",
    "alt": "",
    "name": "10",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/03/25/73856AEXI5NEF_4.png",
    "alt": "",
    "name": "11",
    "link": ""
},
{
    "url": "https://html-generator.com/uploads/images/2023/03/25/75619JC3_B59OWE.png",
    "alt": "",
    "name": "12",
    "link": ""
}
	];

// generated by https://www.html-code-generator.com/html/image-slideshow-generator
	let slider_id = document.querySelector("#hcg-slider-1");

	// append all images
	let dots_div = "";
	let images_div = "";
	for (let i = 0; i < images_list.length; i++) {
		// if no link without href="" tag
		let href = (images_list[i].link == "" ? "":' href="'+images_list[i].link+'"');
		images_div += '<a'+href+' class="hcg-slides animated"'+(i === 0 ? ' style="display:flex"':'')+'>'+
						'<span class="hcg-slide-number">'+(i+1)+'/'+images_list.length+'</span>'+
						'<img src="'+images_list[i].url+'" alt="'+images_list[i].name+'">'+
						'<span class="hcg-slide-text">'+images_list[i].name+'</span>'+
					 '</a>';
		dots_div += '<a href="#" class="hcg-slide-dot'+(i === 0 ? ' dot-active':'')+'" data-id="'+i+'"></a>';
	}
	slider_id.querySelector(".hcg-slider-body").innerHTML = images_div;
	slider_id.querySelector(".hcg-slide-dot-control").innerHTML = dots_div;

	let slide_index = 0;

	const images = slider_id.querySelectorAll(".hcg-slides");
	const dots = slider_id.querySelectorAll(".hcg-slide-dot");
	const prev_button = slider_id.querySelector("#hcg-slide-prev");
	const next_button = slider_id.querySelector("#hcg-slide-next");

	const showSlides = () => {
		if (slide_index > images.length-1) {
			slide_index = 0;
		}
		if (slide_index < 0) {
			slide_index = images.length-1;
		}
		for (let i = 0; i < images.length; i++) {
			images[i].style.display = "none";
			dots[i].classList.remove("dot-active");
			if (i == slide_index) {
				images[i].style.display = "flex";
				dots[i].classList.add("dot-active");
			}
		}
	}

	prev_button.addEventListener("click", event => {
		event.preventDefault();
		slide_index--;
		showSlides();
	}, false);

	next_button.addEventListener("click", event => {
		event.preventDefault();
		slide_index++;
		showSlides();
	}, false);

	const dot_click = event => {
		event.preventDefault();
		slide_index = event.target.dataset.id;
		showSlides();
	}

	for (let i = 0; i < dots.length; i++) {
		dots[i].addEventListener("click", dot_click, false);
	}
})();